#ifndef CONFIG_H
#define CONFIG_H

#define MAX_SESSIONS 3
#define MAX_NICKNAME_LEN 20
#define WINNING_SCORE 5
#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480
#define PADDLE_WIDTH 10
#define PADDLE_HEIGHT 50
#define PADDLE_1_X 10
#define PADDLE_2_X 620
#define BALL_WIDTH 10
#define BALL_HEIGHT 10

#endif // CONFIG_H